### ISSUE TITLE
Issue following your DZone instructions

### ISSUE THREAD

**Issue by edeandrea** [laxika/spring-cloud-function-aws-example#1]
Hi - I came across your article on DZone (https://dzone.com/articles/run-code-with-spring-cloud-function-on-aws-lambda) and thought I would give it a try. After trying it out on my own I was having an issue, which someone else captured here - https://github.com/spring-cloud/spring-cloud-function/issues/113

I did try to clone your repo and follow your instructions exactly, but that doesn't seem to work either.

When I follow your instructions exactly (without modifying anything in your repo) I get this when I try to deploy/run on lambda:

```javascript
{
  "errorMessage": "2017-10-16T18:12:25.852Z 89b1317e-b29d-11e7-b092-7926702960d0 Task timed out after 10.00 seconds"
}
```

```
10/16/2017 14:12:15 EDT	SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
10/16/2017 14:12:15 EDT	SLF4J: Defaulting to no-operation (NOP) logger implementation
10/16/2017 14:12:15 EDT	SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
10/16/2017 14:12:15 EDT	START RequestId: 89b1317e-b29d-11e7-b092-7926702960d0 Version: $LATEST
10/16/2017 14:12:17 EDT	 .   ____          _            __ _ _
10/16/2017 14:12:17 EDT	 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
10/16/2017 14:12:17 EDT	( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
10/16/2017 14:12:17 EDT	 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
10/16/2017 14:12:17 EDT	  '  |____| .__|_| |_|_| |_\__, | / / / /
10/16/2017 14:12:17 EDT	 =========|_|==============|___/=/_/_/_/
10/16/2017 14:12:17 EDT	 :: Spring Boot ::                        
10/16/2017 14:12:18 EDT	
10/16/2017 14:12:25 EDT	END RequestId: 89b1317e-b29d-11e7-b092-7926702960d0
10/16/2017 14:12:25 EDT	REPORT RequestId: 89b1317e-b29d-11e7-b092-7926702960d0	Duration: 10004.82 ms	Billed Duration: 10000 ms 	Memory Size: 512 MB	Max Memory Used: 91 MB	
10/16/2017 14:12:25 EDT	2017-10-16T18:12:25.852Z 89b1317e-b29d-11e7-b092-7926702960d0 Task timed out after 10.00 seconds
10/16/2017 14:12:26 EDT	SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
10/16/2017 14:12:26 EDT	SLF4J: Defaulting to no-operation (NOP) logger implementation
10/16/2017 14:12:26 EDT	SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Any thoughts/ideas?

**Comment by edeandrea** [comment]
Nevermind - I had to increase the startup timeout to something more than 10 seconds

**Comment by maaraoffl** [comment]
@edeandrea I am looking forward to build our service using Spring cloud function. How much seconds in average does it take for your request to be processed in AWS lambda?

**Comment by edeandrea** [comment]
Hi @maheshvra a "cold start" can take sometimes up to 30 seconds, whereas a request where everything is already up & running happens in a few milliseconds.

**Comment by laxika** [comment]
@maheshvra If you use the largest instance and try to slip down spring to it's minimum (excluding unused dependencies) you can get it down to ~3-4 seconds. If you want to use the smallest instance then its anywhere between 30-40 seconds. The main cause of this is that the classloader lacks CPU.
